---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: index.md
  label: Home
  templates:
  - settings
- type: document
  path: work
  label: How we work
- type: directory
  path: capabilities
  label: Capabilities
  create: all
  match: "**/*"
  templates:
  - works
- type: directory
  path: blogs
  label: Blogs
  create: all
  match: "**/[!index]*"
  templates:
  - journal
upload_dir: portfolio/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: portfolio/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run site:develop
